version: '3.8'
services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123   # change before demo if you like
      MYSQL_DATABASE: transport
      MYSQL_USER: transportuser
      MYSQL_PASSWORD: transportpass
    volumes:
      - mysql_data:/var/lib/mysql
      # import initial DB if DB dir empty (place exists in repo)
      - ./transport/transport.sql:/docker-entrypoint-initdb.d/transport.sql:ro
    networks:
      - appnet

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      # these env vars are for demonstration (use them to update the app config)
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: transport
      DB_USERNAME: transportuser
      DB_PASSWORD: transportpass
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword123
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    depends_on:
      - php
      - phpmyadmin
    ports:
      - "80:80"     # http -> redirect to https
      - "443:443"   # https: browser will hit here
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
