version: '3.9'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123   # change before demo if you like
      MYSQL_DATABASE: transport
      MYSQL_USER: transportuser
      MYSQL_PASSWORD: transportpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./transport/transport.sql:/docker-entrypoint-initdb.d/transport.sql:ro
    networks:
      - backend

  frontend:
    build:
      context: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: transport
      DB_USERNAME: transportuser
      DB_PASSWORD: transportpass
    networks:
      - backend
      - frontend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword123
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - phpmyadmin
    ports:
      - "80:80"     # http -> redirect to https
      - "443:443"   # https: browser will hit here
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./proxy/ssl/localhost.key:/etc/ssl/private/localhost.key:ro
    networks:
      - frontend

volumes:
  mysql_data:

networks:
  frontend:
  backend:
