apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "transportsql"
          - name: DB_USERNAME
            value: "transporbanditos"
          - name: DB_PASSWORD
            value: "itbanditos69"

