apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http{
      sendfile on;
      large_client_header_buffers 4 32k;
      }
      upstream frontend-app {
        server frontend:80;
      }
      upstream pma {
        server phpmyadmin:80;
      }
      server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass http://frontend-app;
        }
        location /pma/ {
          proxy_pass http://pma/;
        }
      }
    }
